import { Nunito } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "./globals.css";

export const metadata = {
  title: "Code's Blog",
  description: "Generated by create next app",
};

const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${nunito.variable}`}>
      <body className="text-nunito">
        <div className="max-w-7xl px-4 md:px-8 mx-auto font-sans min-h-screen flex flex-col">
          <Navbar />

          <main className="container px-8 flex-1">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
